; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_ignore =
    Adafruit_TinyUSB_Arduino
    Adafruit TinyUSB Library
framework = arduino
upload_port = /dev/ttyACM0
platform = teensy
upload_protocol = teensy-cli
lib_extra_dirs = ../firmware/lib
build_flags = 
    -I ../config

[env:vattenkar] 
board = teensy40
build_flags = 
    -I ../config
    -D USE_VATTENKAR_CONFIG

[env:esp32]
platform = espressif32
board = nodemcu-32s
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = min_spiffs.csv
monitor_speed = 921600
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0
upload_protocol = esptool

lib_deps =
    ${env.lib_deps}
    madhephaestus/ESP32Servo
    madhephaestus/ESP32Encoder

build_flags =
    -I ../config
    -D __PGMSPACE_H_
    -D USE_ESP32_CONFIG

[env:esp32s2]
platform = espressif32
board = esp32-s2-saola-1
board_build.f_flash = 80000000L
board_build.flash_mode = qio
; board_build.partitions = min_spiffs.csv
monitor_speed = 921600
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0
upload_protocol = esptool
; upload_protocol = espota
; upload_port = 192.168.1.101
; board_microros_transport = wifi
; board_microros_distro = humble
lib_deps =
    ${env.lib_deps}
    madhephaestus/ESP32Servo
    madhephaestus/ESP32Encoder
build_flags =
    -I ../config
;    -D ARDUINO_USB_CDC_ON_BOOT
    -D __PGMSPACE_H_
    -D USE_ESP32S2_CONFIG

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.f_flash = 80000000L
board_build.flash_mode = qio
; board_build.partitions = min_spiffs.csv
monitor_speed = 921600
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
upload_protocol = esptool
; upload_protocol = espota
; upload_port = 192.168.1.101
; board_microros_transport = wifi
; board_microros_distro = humble
lib_deps =
    ${env.lib_deps}
    madhephaestus/ESP32Servo
    madhephaestus/ESP32Encoder
build_flags =
    -I ../config
    -D ARDUINO_USB_CDC_ON_BOOT
    -D __PGMSPACE_H_
    -D USE_ESP32S3_CONFIG

[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
upload_protocol = picotool
board_microros_user_meta = atomic.meta
lib_deps =
    ${env.lib_deps}
    https://github.com/gbr1/rp2040-encoder-library.git
build_flags =
    -I ../config
    -D PICO
    -D PICO2
    -D USE_PICO_CONFIG

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
upload_protocol = picotool
board_microros_user_meta = atomic.meta
lib_deps =
    ${env.lib_deps}
    https://github.com/gbr1/rp2040-encoder-library.git
build_flags =
    -I ../config
    -D PICO
    -D USE_PICO_CONFIG
