; Copyright (c) 2026 Thomas Chou, Linorobot contributors
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.

[platformio]
default_envs = esp32, esp32s2, esp32s3, gendrv

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:esp32]
board = nodemcu-32s
build_flags =
    -I ../config
    -D USE_ESP32_CONFIG

[env:esp32s2]
board = esp32-s2-saola-1
build_flags =
    -I ../config
    -D USE_ESP32S2_CONFIG

[env:esp32s3]
board = esp32-s3-devkitc-1
build_flags =
    -I ../config
    -D USE_ESP32S3_CONFIG

[env:gendrv]
board = nodemcu-32s
build_flags =
    -I ../config
    -D USE_GENDRV_CONFIG
