name: ROS Jazzy Firmware Build

on:
  pull_request:
    # Run on PRs only to branches starting with 'jazzy'
    branches:
      - jazzy*
    # Don't run when the following files are changed which don't effect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  push:
    # Run on pushes only to branches starting with 'jazzy'
    branches:
      - jazzy*
    # Don't run when the following files are changed which don't effect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  # Run Fridays at midnight to detect flakiness and broken dependencies
  schedule:
    - cron: '0 0 * * FRI'

  # Allow manual triggering
  workflow_dispatch:


jobs:
  firmware:
    # The current file calls the firmware workflow with the following parameters
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: jazzy
      os: ubuntu-24.04
      # The reference field will be set to 'jazzy' only if the event that triggered the workflow is schedule. Otherwise, it will be left blank.
      reference: ${{ github.event_name == 'schedule' && 'jazzy' || '' }}
