name: ROS Lyrical Firmware Build

on:
  pull_request:
    branches:
      - lyrical*
      - main
      - devel
      - 'upstream-pr/**'
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  push:
    branches:
      - lyrical*
      - main
      - devel
      - 'upstream-pr/**'
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  schedule:
    - cron: '0 0 * * FRI'

  workflow_dispatch:

jobs:
  firmware:
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: lyrical
      os: ubuntu-24.04
      reference: ${{ github.event_name == 'schedule' && 'lyrical' || '' }}
