name: ROS Rolling Firmware Build

# Get the default branch name from the repository and store it in a variable called DEFAULT_BRANCH
env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

on:
  pull_request:
    # Run on PRs only to branches starting with 'rolling'
    branches:
      - rolling*
    # Don't run when the following files are changed which don't effect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  # Run Fridays at midnight to detect flakiness and broken dependencies
  schedule:
    - cron: '0 0 * * FRI'

  # Allow manual triggering
  workflow_dispatch:


jobs:
  firmware:
    # The current file calls the firmware workflow with the following parameters
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: rolling
      os: ubuntu-24.04
      # The reference field is which branch to build. It will be set to the current default branch of the repository.
      # This is useful for scheduled builds to ensure that the latest code builds against the rolling ROS distro.
      reference: ${{ github.event.repository.default_branch }}
