name: ROS Rolling Firmware Build

on:
  pull_request:
    # Run on PRs to rolling, main, devel, and upstream-pr branches
    branches:
      - rolling*
      - main
      - devel
      - 'upstream-pr/**'
    # Don't run when the following files are changed which don't affect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  push:
    # Run on pushes to rolling, main, devel, and upstream-pr branches
    branches:
      - rolling*
      - main
      - devel
      - 'upstream-pr/**'
    # Don't run when the following files are changed which don't affect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  # Run Fridays at midnight to detect flakiness and broken dependencies
  schedule:
    - cron: '0 0 * * FRI'

  # Allow manual triggering
  workflow_dispatch:


jobs:
  firmware:
    # The current file calls the firmware workflow with the following parameters
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: rolling
      os: ubuntu-24.04
      # The reference field is which branch to build. It will be set to the current default branch of the repository.
      reference: ${{ github.event_name == 'schedule' && 'rolling' || '' }}
